{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "83defac4-814d-490f-84b8-7aa3deb4f3c2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Content saved to output\\bctech2011.txt\n",
      "Content saved to output\\bctech2012.txt\n",
      "Content saved to output\\bctech2013.txt\n",
      "Content saved to output\\bctech2014.txt\n",
      "Content saved to output\\bctech2015.txt\n",
      "Content saved to output\\bctech2016.txt\n",
      "Content saved to output\\bctech2017.txt\n",
      "Content saved to output\\bctech2018.txt\n",
      "Content saved to output\\bctech2019.txt\n",
      "Content saved to output\\bctech2020.txt\n",
      "Content saved to output\\bctech2021.txt\n",
      "Content saved to output\\bctech2022.txt\n",
      "Content saved to output\\bctech2023.txt\n",
      "Content saved to output\\bctech2024.txt\n",
      "Content saved to output\\bctech2025.txt\n",
      "Content saved to output\\bctech2026.txt\n",
      "Content saved to output\\bctech2027.txt\n",
      "Content saved to output\\bctech2028.txt\n",
      "Content saved to output\\bctech2029.txt\n",
      "Content saved to output\\bctech2030.txt\n",
      "Content saved to output\\bctech2031.txt\n",
      "Content saved to output\\bctech2032.txt\n",
      "Content saved to output\\bctech2033.txt\n",
      "Content saved to output\\bctech2034.txt\n",
      "Content saved to output\\bctech2035.txt\n",
      "Content saved to output\\bctech2036.txt\n",
      "Content saved to output\\bctech2037.txt\n",
      "Content saved to output\\bctech2038.txt\n",
      "Content saved to output\\bctech2039.txt\n",
      "Content saved to output\\bctech2040.txt\n",
      "Content saved to output\\bctech2041.txt\n",
      "Content saved to output\\bctech2042.txt\n",
      "Content saved to output\\bctech2043.txt\n",
      "Content saved to output\\bctech2044.txt\n",
      "Content saved to output\\bctech2045.txt\n",
      "Content saved to output\\bctech2046.txt\n",
      "Content saved to output\\bctech2047.txt\n",
      "Content saved to output\\bctech2048.txt\n",
      "Content saved to output\\bctech2049.txt\n",
      "Content saved to output\\bctech2050.txt\n",
      "Content saved to output\\bctech2051.txt\n",
      "Content saved to output\\bctech2052.txt\n",
      "Content saved to output\\bctech2053.txt\n",
      "Content saved to output\\bctech2054.txt\n",
      "Content saved to output\\bctech2055.txt\n",
      "Content saved to output\\bctech2056.txt\n",
      "Content saved to output\\bctech2057.txt\n",
      "Content saved to output\\bctech2058.txt\n",
      "Content saved to output\\bctech2059.txt\n",
      "Content saved to output\\bctech2060.txt\n",
      "Content saved to output\\bctech2061.txt\n",
      "Content saved to output\\bctech2062.txt\n",
      "Content saved to output\\bctech2063.txt\n",
      "Content saved to output\\bctech2064.txt\n",
      "Content saved to output\\bctech2065.txt\n",
      "Content saved to output\\bctech2066.txt\n",
      "Content saved to output\\bctech2067.txt\n",
      "Content saved to output\\bctech2068.txt\n",
      "Content saved to output\\bctech2069.txt\n",
      "Content saved to output\\bctech2070.txt\n",
      "Content saved to output\\bctech2071.txt\n",
      "Content saved to output\\bctech2072.txt\n",
      "Content saved to output\\bctech2073.txt\n",
      "Content saved to output\\bctech2074.txt\n",
      "Content saved to output\\bctech2075.txt\n",
      "Content saved to output\\bctech2076.txt\n",
      "Content saved to output\\bctech2077.txt\n",
      "Content saved to output\\bctech2078.txt\n",
      "Content saved to output\\bctech2079.txt\n",
      "Content saved to output\\bctech2080.txt\n",
      "Content saved to output\\bctech2081.txt\n",
      "Content saved to output\\bctech2082.txt\n",
      "Content saved to output\\bctech2083.txt\n",
      "Content saved to output\\bctech2084.txt\n",
      "Content saved to output\\bctech2085.txt\n",
      "Content saved to output\\bctech2086.txt\n",
      "Content saved to output\\bctech2087.txt\n",
      "Content saved to output\\bctech2088.txt\n",
      "Content saved to output\\bctech2089.txt\n",
      "Content saved to output\\bctech2090.txt\n",
      "Content saved to output\\bctech2091.txt\n",
      "Content saved to output\\bctech2092.txt\n",
      "Content saved to output\\bctech2093.txt\n",
      "Content saved to output\\bctech2094.txt\n",
      "Content saved to output\\bctech2095.txt\n",
      "Content saved to output\\bctech2096.txt\n",
      "Content saved to output\\bctech2097.txt\n",
      "Content saved to output\\bctech2098.txt\n",
      "Content saved to output\\bctech2099.txt\n",
      "Content saved to output\\bctech2100.txt\n",
      "Content saved to output\\bctech2101.txt\n",
      "Content saved to output\\bctech2102.txt\n",
      "Content saved to output\\bctech2103.txt\n",
      "Content saved to output\\bctech2104.txt\n",
      "Content saved to output\\bctech2105.txt\n",
      "Content saved to output\\bctech2106.txt\n",
      "Content saved to output\\bctech2107.txt\n",
      "Content saved to output\\bctech2108.txt\n",
      "Content saved to output\\bctech2109.txt\n",
      "Content saved to output\\bctech2110.txt\n",
      "Content saved to output\\bctech2111.txt\n",
      "Content saved to output\\bctech2112.txt\n",
      "Content saved to output\\bctech2113.txt\n",
      "Content saved to output\\bctech2114.txt\n",
      "Content saved to output\\bctech2115.txt\n",
      "Content saved to output\\bctech2116.txt\n",
      "Content saved to output\\bctech2117.txt\n",
      "Content saved to output\\bctech2118.txt\n",
      "Content saved to output\\bctech2119.txt\n",
      "Content saved to output\\bctech2120.txt\n",
      "Content saved to output\\bctech2121.txt\n",
      "Content saved to output\\bctech2122.txt\n",
      "Content saved to output\\bctech2123.txt\n",
      "Content saved to output\\bctech2124.txt\n",
      "Content saved to output\\bctech2125.txt\n",
      "Content saved to output\\bctech2126.txt\n",
      "Content saved to output\\bctech2127.txt\n",
      "Content saved to output\\bctech2128.txt\n",
      "Content saved to output\\bctech2129.txt\n",
      "Content saved to output\\bctech2130.txt\n",
      "Content saved to output\\bctech2131.txt\n",
      "Content saved to output\\bctech2132.txt\n",
      "Content saved to output\\bctech2133.txt\n",
      "Content saved to output\\bctech2134.txt\n",
      "Content saved to output\\bctech2135.txt\n",
      "Content saved to output\\bctech2136.txt\n",
      "Content saved to output\\bctech2137.txt\n",
      "Content saved to output\\bctech2138.txt\n",
      "Content saved to output\\bctech2139.txt\n",
      "Content saved to output\\bctech2140.txt\n",
      "Content saved to output\\bctech2141.txt\n",
      "Content saved to output\\bctech2142.txt\n",
      "Content saved to output\\bctech2143.txt\n",
      "Content saved to output\\bctech2144.txt\n",
      "Content saved to output\\bctech2145.txt\n",
      "Content saved to output\\bctech2146.txt\n",
      "Content saved to output\\bctech2147.txt\n",
      "Content saved to output\\bctech2148.txt\n",
      "Content saved to output\\bctech2149.txt\n",
      "Content saved to output\\bctech2150.txt\n",
      "Content saved to output\\bctech2151.txt\n",
      "Content saved to output\\bctech2152.txt\n",
      "Content saved to output\\bctech2153.txt\n",
      "Content saved to output\\bctech2154.txt\n",
      "Content saved to output\\bctech2155.txt\n",
      "Content saved to output\\bctech2156.txt\n",
      "Content saved to output\\bctech2157.txt\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import os\n",
    "\n",
    "# Function to fetch and parse a webpage\n",
    "def fetch_and_parse(url):\n",
    "    response = requests.get(url)\n",
    "    if response.status_code == 200:\n",
    "        return BeautifulSoup(response.content, 'html.parser')\n",
    "    else:\n",
    "        print(f\"Failed to fetch {url}\")\n",
    "        return None\n",
    "\n",
    "# Function to extract the desired content\n",
    "def extract_content(soup):\n",
    "    if not soup:\n",
    "        return None, None\n",
    "    \n",
    "    h1_tag = soup.find('h1')\n",
    "    div_tag = soup.find('div', class_='td-post-content tagdiv-type')\n",
    "\n",
    "    h1_text = h1_tag.get_text(strip=True) if h1_tag else 'No H1 tag found'\n",
    "    div_text = div_tag.get_text() if div_tag else 'No matching div found'\n",
    "    \n",
    "    return h1_text, div_text\n",
    "\n",
    "# Function to save content to a file\n",
    "def save_to_file(filename, h1_text, div_text):\n",
    "    with open(filename, 'w', encoding='utf-8') as file:\n",
    "        file.write(f\"H1 Text:\\n{h1_text}\\n\\n\")\n",
    "        file.write(f\"Div Text:\\n{div_text}\\n\")\n",
    "\n",
    "# Main function to process multiple URLs\n",
    "def process_urls(urls):\n",
    "    if not os.path.exists('output'):\n",
    "        os.makedirs('output')\n",
    "    \n",
    "    for idx, url in enumerate(urls):\n",
    "        soup = fetch_and_parse(url)\n",
    "        h1_text, div_text = extract_content(soup)\n",
    "        filename = os.path.join('output', f'bctech{idx+1+2010}.txt')\n",
    "        save_to_file(filename, h1_text, div_text)\n",
    "        print(f\"Content saved to {filename}\")\n",
    "\n",
    "# List of URLs to process\n",
    "urls = [\n",
    "'https://insights.blackcoffer.com/ml-and-ai-based-insurance-premium-model-to-predict-premium-to-be-charged-by-the-insurance-company/',\n",
    "'https://insights.blackcoffer.com/streamlined-integration-interactive-brokers-api-with-python-for-desktop-trading-application/',\n",
    "'https://insights.blackcoffer.com/efficient-data-integration-and-user-friendly-interface-development-navigating-challenges-in-web-application-deployment/',\n",
    "'https://insights.blackcoffer.com/effective-management-of-social-media-data-extraction-strategies-for-authentication-security-and-reliability/',\n",
    "'https://insights.blackcoffer.com/streamlined-trading-operations-interface-for-metatrader-4-empowering-efficient-management-and-monitoring/',\n",
    "'https://insights.blackcoffer.com/efficient-aws-infrastructure-setup-and-management-addressing-security-scalability-and-compliance/',\n",
    "'https://insights.blackcoffer.com/streamlined-equity-waterfall-calculation-and-deal-management-system/',\n",
    "'https://insights.blackcoffer.com/automated-orthopedic-case-report-generation-harnessing-web-scraping-and-ai-integration/',\n",
    "'https://insights.blackcoffer.com/streamlining-time-calculation-in-warehouse-management-leveraging-shiphero-api-and-google-bigquery-integration/',\n",
    "'https://insights.blackcoffer.com/efficient-database-design-and-management-streamlining-access-and-integration-for-partner-entity-management/',\n",
    "'https://insights.blackcoffer.com/automated-campaign-management-system-a-comprehensive-solution-with-linkedin-and-email-integration/',\n",
    "'https://insights.blackcoffer.com/ai-driven-data-analysis-ai-tool-using-langchain-for-a-leading-real-estate-and-financing-firm-worldwide/',\n",
    "'https://insights.blackcoffer.com/grafana-dashboard-to-visualize-and-analyze-sensors-data/',\n",
    "'https://insights.blackcoffer.com/mvp-for-a-software-that-analyses-content-from-audio-pharma-based/',\n",
    "'https://insights.blackcoffer.com/data-engineering-and-management-tool-airbyte-with-custom-data-connectors-to-manage-crm-database/',\n",
    "'https://insights.blackcoffer.com/text-summarizing-tool-to-scrape-and-summarize-pubmed-medical-papers/',\n",
    "'https://insights.blackcoffer.com/7up7down-10updown-snakes-and-ladder-games-built-using-oops/',\n",
    "'https://insights.blackcoffer.com/data-studio-dashboard-with-a-data-pipeline-tool-synced-with-podio-using-custom-webhooks-and-google-cloud-function/',\n",
    "'https://insights.blackcoffer.com/end-to-end-tool-to-optimize-routing-and-planning-of-field-engineers-using-googles-cvrp-tw-algorithm/',\n",
    "'https://insights.blackcoffer.com/end-to-end-tool-to-predict-biofuel-prices-using-ieso-data/',\n",
    "'https://insights.blackcoffer.com/etl-discovery-tool-using-llma-langchain-openai/',\n",
    "'https://insights.blackcoffer.com/gpt-ocr-api/',\n",
    "'https://insights.blackcoffer.com/dockerize-the-aws-lambda-for-serverless-architecture/',\n",
    "'https://insights.blackcoffer.com/design-and-develop-a-product-recommendation-engine-based-on-the-features-of-products/',\n",
    "'https://insights.blackcoffer.com/database-discovery-tool-using-openai/',\n",
    "'https://insights.blackcoffer.com/automate-the-data-management-process/',\n",
    "'https://insights.blackcoffer.com/realtime-kibana-dashboard-for-a-financial-tech-firm/',\n",
    "'https://insights.blackcoffer.com/data-management-etl-and-data-automation/',\n",
    "'https://insights.blackcoffer.com/data-management-egeas/',\n",
    "'https://insights.blackcoffer.com/design-and-develop-powershell-script/',\n",
    "'https://insights.blackcoffer.com/design-and-develop-jenkins-shared-library/',\n",
    "'https://insights.blackcoffer.com/design-and-develop-retool-app-for-wholecell-io-and-asana-data-using-their-apis/',\n",
    "'https://insights.blackcoffer.com/design-and-develop-a-retool-app-that-will-show-stock-and-crypto-related-information-using-iex-api/',\n",
    "'https://insights.blackcoffer.com/crm-monday-com-make-com-to-data-warehouse-to-klipfolio-dashboard/',\n",
    "'https://insights.blackcoffer.com/ner-task-using-bert-with-data-in-xml-format/',\n",
    "'https://insights.blackcoffer.com/qualtrics-api-integration-using-python/',\n",
    "'https://insights.blackcoffer.com/design-and-develop-mlops-framework-for-data-centric-ai/',\n",
    "'https://insights.blackcoffer.com/nlp-based-approach-for-data-transformation/',\n",
    "'https://insights.blackcoffer.com/an-etl-tool-to-pull-data-from-shiphero-to-google-bigquery-data-warehouse/',\n",
    "'https://insights.blackcoffer.com/plaid-financial-analytics-a-data-driven-dashboard-to-generate-insights/',\n",
    "'https://insights.blackcoffer.com/recommendation-engine-for-insurance-sector-to-expand-business-in-the-rural-area/',\n",
    "'https://insights.blackcoffer.com/data-from-crm-via-zapier-to-google-sheets-dynamic-to-powerbi/',\n",
    "'https://insights.blackcoffer.com/data-warehouse-to-google-data-studio-looker-dashboard/',\n",
    "'https://insights.blackcoffer.com/crm-monday-com-via-zapier-to-power-bi-dashboard/',\n",
    "'https://insights.blackcoffer.com/monday-com-to-kpi-dashboard-to-manage-view-and-generate-insights-from-the-crm-data/',\n",
    "'https://insights.blackcoffer.com/data-management-for-a-political-saas-application/',\n",
    "'https://insights.blackcoffer.com/google-lsa-ads-google-local-service-ads-etl-tools-and-dashboards/',\n",
    "'https://insights.blackcoffer.com/ad-networks-marketing-campaign-data-dashboard-in-looker-google-data-studio/',\n",
    "'https://insights.blackcoffer.com/analytical-solution-for-a-tech-firm/',\n",
    "'https://insights.blackcoffer.com/ai-solution-for-a-technology-information-and-internet-firm/',\n",
    "'https://insights.blackcoffer.com/ai-and-nlp-based-solutions-to-automate-data-discovery-for-venture-capital-and-private-equity-principals/',\n",
    "'https://insights.blackcoffer.com/an-etl-solution-for-an-internet-publishing-firm/',\n",
    "'https://insights.blackcoffer.com/ai-based-algorithmic-trading-bot-for-forex/',\n",
    "'https://insights.blackcoffer.com/equity-waterfalls-model-based-saas-application-for-real-estate-sector/',\n",
    "'https://insights.blackcoffer.com/ai-solutions-for-foreign-exchange-an-automated-algo-trading-tool/',\n",
    "'https://insights.blackcoffer.com/ai-agent-development-and-deployment-in-jina-ai/',\n",
    "'https://insights.blackcoffer.com/golden-record-a-knowledge-graph-database-approach-to-unfold-discovery-using-neo4j/',\n",
    "'https://insights.blackcoffer.com/advanced-ai-for-trading-automation/',\n",
    "'https://insights.blackcoffer.com/create-a-knowledge-graph-to-provide-real-time-analytics-recommendations-and-a-single-source-of-truth/',\n",
    "'https://insights.blackcoffer.com/advanced-ai-for-thermal-person-detection/',\n",
    "'https://insights.blackcoffer.com/advanced-ai-for-road-cam-threat-detection/',\n",
    "'https://insights.blackcoffer.com/advanced-ai-for-pedestrian-crossing-safety/',\n",
    "'https://insights.blackcoffer.com/handgun-detection-using-yolo/',\n",
    "'https://insights.blackcoffer.com/using-graph-technology-to-create-single-customer-view/',\n",
    "'https://insights.blackcoffer.com/car-detection-in-satellite-images/',\n",
    "'https://insights.blackcoffer.com/building-a-physics-informed-neural-network-for-circuit-evaluation/',\n",
    "'https://insights.blackcoffer.com/connecting-mongodb-database-to-power-bi-dashboard-dashboard-automation/',\n",
    "'https://insights.blackcoffer.com/data-transformation/',\n",
    "'https://insights.blackcoffer.com/e-commerce-store-analysis-purchase-behavior-ad-spend-conversion-traffic-etc/',\n",
    "'https://insights.blackcoffer.com/kpi-dashboard-for-accountants/',\n",
    "'https://insights.blackcoffer.com/return-on-advertising-spend-dashboard-marketing-automation-and-analytics-using-etl-and-dashboard/',\n",
    "'https://insights.blackcoffer.com/ranking-customer-behaviours-for-business-strategy/',\n",
    "'https://insights.blackcoffer.com/algorithmic-trading-for-multiple-commodities-markets-like-forex-metals-energy-etc/',\n",
    "'https://insights.blackcoffer.com/trading-bot-for-forex/',\n",
    "'https://insights.blackcoffer.com/python-model-for-the-analysis-of-sector-specific-stock-etfs-for-investment-purposes%ef%bf%bc/',\n",
    "'https://insights.blackcoffer.com/medical-classification/',\n",
    "'https://insights.blackcoffer.com/design-develop-bert-question-answering-model-explanations-with-visualization/',\n",
    "'https://insights.blackcoffer.com/design-and-develop-solution-to-anomaly-detection-classification-problems/',\n",
    "'https://insights.blackcoffer.com/an-etl-solution-for-currency-data-to-google-big-query/',\n",
    "'https://insights.blackcoffer.com/etl-and-mlops-infrastructure-for-blockchain-analytics/',\n",
    "'https://insights.blackcoffer.com/an-agent-based-model-of-a-virtual-power-plant-vpp/',\n",
    "'https://insights.blackcoffer.com/transform-api-into-sdk-library-and-widget/',\n",
    "'https://insights.blackcoffer.com/integration-of-a-product-to-a-cloud-based-crm-platform/',\n",
    "'https://insights.blackcoffer.com/a-web-based-dashboard-for-the-filtered-data-retrieval-of-land-records/',\n",
    "'https://insights.blackcoffer.com/integration-of-video-conferencing-data-to-the-existing-web-app/',\n",
    "'https://insights.blackcoffer.com/design-develop-an-app-in-retool-which-shows-the-progress-of-the-added-video/',\n",
    "'https://insights.blackcoffer.com/auvik-connectwise-integration-in-grafana/',\n",
    "'https://insights.blackcoffer.com/data-integration-and-big-data-performance-using-elk-stack/',\n",
    "'https://insights.blackcoffer.com/web-data-connector/',\n",
    "'https://insights.blackcoffer.com/an-app-for-updating-the-email-id-of-the-user-and-stripe-refund-tool-using-retool/',\n",
    "'https://insights.blackcoffer.com/an-ai-ml-based-web-application-that-detects-the-correctness-of-text-in-a-given-video/',\n",
    "'https://insights.blackcoffer.com/website-tracking-and-insights-using-google-analytics-google-tag-manager/',\n",
    "'https://insights.blackcoffer.com/dashboard-to-track-the-analytics-of-the-website-using-google-analytics-and-google-tag-manager/',\n",
    "'https://insights.blackcoffer.com/power-bi-dashboard-on-operations-transactions-and-marketing-embedding-the-dashboard-to-web-app/',\n",
    "'https://insights.blackcoffer.com/nft-data-automation-looksrare-and-etl-tool/',\n",
    "'https://insights.blackcoffer.com/optimize-the-data-scraper-program-to-easily-accommodate-large-files-and-solve-oom-errors/',\n",
    "'https://insights.blackcoffer.com/making-a-robust-way-to-sync-data-from-airtables-to-mongodb-using-python-etl-solution/',\n",
    "'https://insights.blackcoffer.com/incident-duration-prediction-infrastructure-and-real-estate/',\n",
    "'https://insights.blackcoffer.com/statistical-data-analysis-of-reinforced-concrete/',\n",
    "'https://insights.blackcoffer.com/database-normalization-segmentation-with-google-data-studio-dashboard-insights/',\n",
    "'https://insights.blackcoffer.com/power-bi-dashboard-to-drive-insights-from-complex-data-to-generate-business-insights/',\n",
    "'https://insights.blackcoffer.com/real-time-dashboard-to-monitor-infrastructure-activity-and-machines/',\n",
    "'https://insights.blackcoffer.com/electric-vehicles-ev-load-management-system-to-forecast-energy-demand/',\n",
    "'https://insights.blackcoffer.com/power-bi-data-driven-map-dashboard/',\n",
    "'https://insights.blackcoffer.com/google-local-service-ads-lsa-leads-dashboard/',\n",
    "'https://insights.blackcoffer.com/aws-lex-voice-and-chatbot/',\n",
    "'https://insights.blackcoffer.com/metabridges-api-decentraland-integration/',\n",
    "'https://insights.blackcoffer.com/microsoft-azure-chatbot-with-luis-language-understanding/',\n",
    "'https://insights.blackcoffer.com/impact-of-news-media-and-press-on-innovation-startups-and-investments/',\n",
    "'https://insights.blackcoffer.com/aws-quicksight-reporting-dashboard/',\n",
    "'https://insights.blackcoffer.com/google-data-studio-dashboard-for-marketing-ads-and-traction-data/',\n",
    "'https://insights.blackcoffer.com/gangala-in-e-commerce-big-data-etl-elt-solution-and-data-warehouse/',\n",
    "'https://insights.blackcoffer.com/big-data-solution-to-an-online-multivendor-marketplace-ecommerce-business/',\n",
    "'https://insights.blackcoffer.com/creating-a-custom-report-and-dashboard-using-the-data-got-from-atera-api/',\n",
    "'https://insights.blackcoffer.com/azure-data-lake-and-power-bi-dashboard/',\n",
    "'https://insights.blackcoffer.com/google-data-studio-pipeline-with-gcp-mysql/',\n",
    "'https://insights.blackcoffer.com/quickbooks-dashboard-to-find-patterns-in-finance-sales-and-forecasts/',\n",
    "'https://insights.blackcoffer.com/marketing-sales-and-financial-data-business-dashboard-wink-report/',\n",
    "'https://insights.blackcoffer.com/react-native-apps-in-the-development-portfolio/',\n",
    "'https://insights.blackcoffer.com/a-leading-firm-website-seo-optimization/',\n",
    "'https://insights.blackcoffer.com/a-leading-hospitality-firm-in-the-usa-website-seo-optimization/',\n",
    "'https://insights.blackcoffer.com/a-leading-firm-in-the-usa-website-seo-optimization/',\n",
    "'https://insights.blackcoffer.com/a-leading-musical-instrumental-website-seo-optimization/',\n",
    "'https://insights.blackcoffer.com/a-leading-firm-in-the-usa-seo-and-website-optimization/',\n",
    "'https://insights.blackcoffer.com/immigration-datawarehouse-ai-based-recommendations/',\n",
    "'https://insights.blackcoffer.com/lipsync-automation-for-celebrities-and-influencers/',\n",
    "'https://insights.blackcoffer.com/key-audit-matters-predictive-modeling/',\n",
    "'https://insights.blackcoffer.com/splitting-of-songs-into-its-vocals-and-instrumental/',\n",
    "'https://insights.blackcoffer.com/ai-and-ml-technologies-to-evaluate-learning-assessments/',\n",
    "'https://insights.blackcoffer.com/datawarehouse-and-recommendations-engine-for-airbnb/',\n",
    "'https://insights.blackcoffer.com/real-estate-data-warehouse/',\n",
    "'https://insights.blackcoffer.com/traction-dashboards-of-marketing-campaigns-and-posts/',\n",
    "'https://insights.blackcoffer.com/google-local-service-ads-lsa-data-warehouse/',\n",
    "'https://insights.blackcoffer.com/google-local-service-ads-missed-calls-and-messages-automation-tool/',\n",
    "'https://insights.blackcoffer.com/marketing-ads-leads-call-status-data-tool-to-bigquery/',\n",
    "'https://insights.blackcoffer.com/marketing-analytics-to-automate-leads-call-status-and-reporting/',\n",
    "'https://insights.blackcoffer.com/callrail-analytics-leads-report-alert/',\n",
    "'https://insights.blackcoffer.com/marketing-automation-tool-to-notify-lead-details-to-clients-over-email-and-phone/',\n",
    "'https://insights.blackcoffer.com/data-etl-local-service-ads-leads-to-bigquery/',\n",
    "'https://insights.blackcoffer.com/marbles-stimulation-using-python/',\n",
    "'https://insights.blackcoffer.com/stocktwits-data-structurization/',\n",
    "'https://insights.blackcoffer.com/sentimental-analysis-on-shareholder-letter-of-companies/',\n",
    "'https://insights.blackcoffer.com/population-and-community-survey-of-america/',\n",
    "'https://insights.blackcoffer.com/google-lsa-api-data-automation-and-dashboarding/',\n",
    "'https://insights.blackcoffer.com/healthcare-data-analysis/',\n",
    "'https://insights.blackcoffer.com/budget-sales-kpi-dashboard-using-power-bi/',\n",
    "'https://insights.blackcoffer.com/amazon-buy-bot-an-automation-ai-tool-to-auto-checkouts/'\n",
    "    # Add more URLs as needed\n",
    "]\n",
    "\n",
    "# Run the script\n",
    "process_urls(urls)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "db0def81-fb67-4820-9eee-798eb89d350e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64aa35dd-d58f-4136-9141-fb112e3a29a2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
